-- events.db :: events table
--
-- Canonical schema: mirrors the "Event schema" section of the root
-- CLAUDE.md, and the enums in shared/config.py (BEHAVIOUR_TYPES,
-- RISK_LEVELS) — those Python lists are the actual source of truth;
-- the CHECK constraints below are a hardcoded mirror kept for
-- defense-in-depth at the DB layer. If the enum ever changes, update
-- shared/config.py first (Python validation in store.py reads from
-- there directly, so it can't drift), then update this file to match.

CREATE TABLE IF NOT EXISTS events (
    event_id             TEXT PRIMARY KEY,                 -- e.g. "evt_00042" — generated by Member 2's engine, not here
    timestamp            TEXT NOT NULL,                     -- ISO-8601 UTC, when the event occurred
    behaviour_type        TEXT NOT NULL CHECK (behaviour_type IN (
        'dropped', 'dragged', 'rough_handling', 'stepping_on_product',
        'incorrect_stacking', 'unstable_stacking', 'outside_designated_area',
        'no_required_equipment', 'pallet_incorrect_position', 'pushed_or_thrown',
        'unsafe_loading_sequence', 'rolling', 'wrong_orientation', 'strap_misuse'
    )),
    risk_level             TEXT NOT NULL CHECK (risk_level IN ('Low', 'Medium', 'High', 'Critical')),
    risk_score              REAL NOT NULL CHECK (risk_score >= 0.0 AND risk_score <= 1.0),
    bay                    TEXT NOT NULL,
    object_ids              TEXT NOT NULL,                   -- JSON array of track_ids, e.g. "[7, 3]"
    evidence_frame_path      TEXT NOT NULL,                   -- e.g. "shared/evidence/evt_00042.jpg"
    explanation             TEXT NOT NULL,                   -- bad-practice -> good-practice text, from Member 2
    created_at              TEXT NOT NULL                    -- ISO-8601 UTC, set here at insert time (not the event time)
);

CREATE INDEX IF NOT EXISTS idx_events_timestamp      ON events (timestamp);
CREATE INDEX IF NOT EXISTS idx_events_bay            ON events (bay);
CREATE INDEX IF NOT EXISTS idx_events_risk_level     ON events (risk_level);
CREATE INDEX IF NOT EXISTS idx_events_behaviour_type ON events (behaviour_type);

-- Note: there is no "activity" (loading/unloading/handling) or "shift"
-- column. Neither is part of the shared event schema anyone else in the
-- team builds against, and the pilot's scope is a single loading/
-- unloading process in one bay (see docs/AI_Video_Intelligence_Project_Spec.md
-- §2), so "activity" isn't a real dimension yet. "shift" is derived from
-- `timestamp` at query time instead of stored — see store.py's
-- `_shift_for_hour()`, which uses the same Morning/Evening/Night, 6/14/22
-- boundaries as dashboard/config.py's SHIFTS, so both modules group
-- shifts identically.
