"""
dashboard/ui.py — shared Streamlit UI building blocks used by app.py and every
page: path bootstrap, sidebar, data loading with honest empty/error states,
and the SAMPLE DATA badge.
"""

from __future__ import annotations

import sys
from pathlib import Path

# --- bootstrap: make repo root + dashboard importable from any page ------
# app.py lives in dashboard/, pages live in dashboard/pages/ — both end up
# with dashboard/ and the repo root on sys.path.
_here = Path(__file__).resolve().parent
for _p in (str(_here), str(_here.parent)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import pandas as pd
import streamlit as st

import config  # dashboard/config.py
import data_access

# Session-state key under which the loaded events DataFrame is cached.
EVENTS_KEY = "events_df"
SOURCE_KEY = "data_source"


@st.cache_data(show_spinner="Loading event store…")
def _load_events_cached(db_path: str) -> pd.DataFrame:
    return data_access.load_events(db_path)


def load_state() -> bool:
    """Resolve the data source and load events into session state.

    Returns True when events are available to render. Renders the honest
    empty/error state itself and returns False when they're not — callers
    should simply stop rendering after a False.
    """
    source = config.resolve_data_source()
    st.session_state[SOURCE_KEY] = source

    if not source["available"]:
        _empty_state(source)
        return False

    try:
        df = _load_events_cached(source["db_path"])
    except Exception as exc:
        st.error(f"Could not read the event store: {exc}")
        st.caption(f"Attempted path: `{source['db_path']}`")
        return False

    if df.empty:
        _empty_state(source, empty_table=True)
        return False

    st.session_state[EVENTS_KEY] = df
    return True


def require_events():
    """Guard used at the top of each page: loads state, stops the page if
    there is nothing honest to show."""
    ok = load_state()
    if not ok:
        st.stop()
    return st.session_state[EVENTS_KEY]


def sidebar() -> dict:
    """Render the shared sidebar: title, data-source status, sample badge."""
    source = st.session_state.get(SOURCE_KEY, {})
    with st.sidebar:
        st.markdown("## 🏭 Warehouse-AI")
        st.caption("Damage prevention through behaviour intelligence")

        if source.get("is_sample"):
            st.error(
                "**SAMPLE DATA** — generated by `dashboard/test_data/` for demo "
                "purposes. Not real pipeline output.",
                icon="🧪",
            )
        elif source.get("available"):
            st.success("**LIVE EVENT STORE** — real pipeline output.", icon="✅")

        st.divider()
        st.markdown("**Data source**")
        st.caption(f"Event store: `{source.get('db_path', '—')}`")
        st.caption(f"Evidence dir: `{source.get('evidence_dir', '—')}`")
        if source.get("reason"):
            st.info(source["reason"], icon="ℹ️")
        return source


def _empty_state(source: dict, empty_table: bool = False):
    """Honest empty state — what's missing and exactly how to fix it."""
    if empty_table:
        st.warning(
            "The event store is connected but contains **0 events**. The "
            "dashboard will populate automatically as Member 2's behaviour "
            "engine writes events. Nothing is shown here because there is "
            "nothing to show.", icon="📭"
        )
        return
    st.warning(
        "**No event store found.** The dashboard reads `backend-assistant/events.db` "
        "(Member 3's event store) and renders nothing until real events exist.\n\n"
        "To explore the UI with clearly-labelled sample data instead, generate it:\n"
        "```\npython dashboard/test_data/generate_test_data.py\n```\n"
        "Then reload — the dashboard auto-detects the sample store and badges "
        "every page with **SAMPLE DATA**.",
        icon="🔌",
    )
    st.caption(f"Looked for the real store at: `{config.EVENTS_DB_PATH}`")


def kpi_columns(n: int):
    return st.columns(n)


def risk_pill(level: str) -> str:
    """Unicode pill used in tables/markdown — color-stable per risk level."""
    return {
        "Low": "🟢 Low",
        "Medium": "🟡 Medium",
        "High": "🟠 High",
        "Critical": "🔴 Critical",
    }.get(level, level)
